### PR TITLE
Feature extraction from mixed cuts

### PR DESCRIPTION
**Pull request by pzelasko**

### CODE REVIEW

**Comment by pzelasko** [comment]
@danpovey ok to review

**Review by danpovey — COMMENTED** [review]
LGTM!
Was this in response to a conversation with Paola?
She was concerned about what happens where the audio is extremely long and we don't want to load it all at once.

**Comment by pzelasko** [comment]
Actually no, we haven't talked (yet). It's adding a missing feature - I
implemented feature extraction from Cuts before, but it didn't support
MixedCuts. I also saw an opportunity to get rid of librosa as a core
dependency - it installs ~20 other deps. The audio was already being read
partially before though.

śr., 16 wrz 2020, 00:21 użytkownik Daniel Povey <notifications@github.com>
napisał:

**Comment by danpovey** [comment]
Great!

**Pull request merged**
